### ISSUE TITLE
Missing Package.xml

### ISSUE THREAD

**Issue by britishboyindc** [cslogan-red/df_2016_demo#1]
Anyway you can add the package.xml file to the repo? Without that, you can't install via Andy Fawcett's deployment tool so have to download and deploy via Ant or IDE which is a pain...

Thanks!

**Comment by cslogan-red** [comment]
Had it in my `.gitignore` file so I missed it, removed and committed! Also note on the API key in the updated README if you try to use the app. I've included my free dev key in `WeatherStatics.cls` but it's limited on requests per hour, sign up for your own free key and replace mine if you run into trouble. Thanks!
