### ISSUE TITLE
Locker Service breaks the Cookie functionality?

### ISSUE THREAD

**Issue by britishboyindc** [cslogan-red/df_2016_demo#3]
Running this in a new dev org, and Locker Service was enabled automatically, which seems to break the Cookie Session Storage functionality. Once I disabled critical update for Locker Service, worked ok, but might be worth noting in readme...

**Comment by cslogan-red** [comment]
Valid point! 👍  This was originally written before that update was introduced and I went back and half-way made the changes to support Locker Service and never quite finished the rest, there are a couple of places that the traditional JS DOM selectors need to be replaced with Lightning framework equivalents, or the update must be disabled. Updated README to reflect!
